// Auto-generated — do not edit by hand
#pragma once
#include <Arduino.h>

const char INDEX_HTML[] PROGMEM =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>BECA Control</title>\n"
"    <style>\n"
"      :root {\n"
"        color-scheme: light;\n"
"        --bg: #edf3ed;\n"
"        --bg-deep: #d7e6dc;\n"
"        --panel: rgba(255, 255, 255, 0.84);\n"
"        --panel-soft: rgba(248, 251, 248, 0.72);\n"
"        --edge: rgba(0, 131, 81, 0.18);\n"
"        --edge-strong: rgba(0, 131, 81, 0.28);\n"
"        --accent: #008351;\n"
"        --accent-strong: #05663f;\n"
"        --accent-soft: rgba(0, 131, 81, 0.12);\n"
"        --text: #133126;\n"
"        --text-soft: rgba(19, 49, 38, 0.68);\n"
"        --muted: #cad8ce;\n"
"        --muted-deep: #b6c8bc;\n"
"        --white: #ffffff;\n"
"        --warn: #d48a00;\n"
"        --danger: #db5d38;\n"
"        --shadow: 0 20px 48px rgba(16, 41, 30, 0.12);\n"
"        --shadow-soft: 0 10px 24px rgba(0, 131, 81, 0.12);\n"
"        --radius-xl: 32px;\n"
"        --radius-lg: 22px;\n"
"        --radius-md: 16px;\n"
"        --radius-sm: 12px;\n"
"        --mono:\n"
"          \"Geist Mono\",\n"
"          \"SFMono-Regular\",\n"
"          \"JetBrains Mono\",\n"
"          \"Consolas\",\n"
"          monospace;\n"
"        --display:\n"
"          \"Avenir Next\",\n"
"          \"SF Pro Display\",\n"
"          \"Helvetica Neue\",\n"
"          sans-serif;\n"
"      }\n"
"\n"
"      * {\n"
"        box-sizing: border-box;\n"
"      }\n"
"\n"
"      html,\n"
"      body {\n"
"        margin: 0;\n"
"        min-height: 100%;\n"
"      }\n"
"\n"
"      body {\n"
"        background:\n"
"          radial-gradient(880px 520px at 84% -8%, rgba(0, 131, 81, 0.18), transparent 60%),\n"
"          radial-gradient(820px 620px at 10% 18%, rgba(141, 198, 154, 0.2), transparent 64%),\n"
"          linear-gradient(165deg, var(--bg) 0%, var(--bg-deep) 52%, var(--bg) 100%);\n"
"        color: var(--text);\n"
"        font-family: var(--display);\n"
"      }\n"
"\n"
"      body::before {\n"
"        content: \"\";\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background-image:\n"
"          linear-gradient(rgba(0, 131, 81, 0.045) 1px, transparent 1px),\n"
"          linear-gradient(90deg, rgba(0, 131, 81, 0.045) 1px, transparent 1px);\n"
"        background-size: 30px 30px;\n"
"        opacity: 0.32;\n"
"        pointer-events: none;\n"
"        z-index: -1;\n"
"      }\n"
"\n"
"      button,\n"
"      select,\n"
"      input {\n"
"        font: inherit;\n"
"      }\n"
"\n"
"      button {\n"
"        cursor: pointer;\n"
"      }\n"
"\n"
"      .beca-app {\n"
"        width: min(1480px, 100%);\n"
"        margin: 0 auto;\n"
"        padding: clamp(16px, 2vw, 28px);\n"
"      }\n"
"\n"
"      .surface {\n"
"        position: relative;\n"
"        display: grid;\n"
"        gap: clamp(16px, 1.8vw, 24px);\n"
"        padding: clamp(18px, 2vw, 28px);\n"
"        border: 1px solid var(--edge-strong);\n"
"        border-radius: var(--radius-xl);\n"
"        background:\n"
"          linear-gradient(145deg, rgba(255, 255, 255, 0.92), rgba(240, 247, 242, 0.76)),\n"
"          var(--panel);\n"
"        box-shadow: var(--shadow);\n"
"        overflow: hidden;\n"
"      }\n"
"\n"
"      .surface::before {\n"
"        content: \"\";\n"
"        position: absolute;\n"
"        inset: 0;\n"
"        background:\n"
"          radial-gradient(420px 280px at 82% 85%, rgba(0, 131, 81, 0.1), transparent 64%),\n"
"          linear-gradient(135deg, rgba(255, 255, 255, 0.38), transparent 48%);\n"
"        pointer-events: none;\n"
"      }\n"
"\n"
"      .surface > * {\n"
"        position: relative;\n"
"        z-index: 1;\n"
"      }\n"
"\n"
"      .surface-header {\n"
"        display: flex;\n"
"        justify-content: space-between;\n"
"        align-items: flex-start;\n"
"        gap: 20px;\n"
"      }\n"
"\n"
"      .brand-area {\n"
"        display: flex;\n"
"        gap: 16px;\n"
"        align-items: flex-start;\n"
"      }\n"
"\n"
"      .logo-lockup {\n"
"        width: clamp(96px, 9vw, 122px);\n"
"        color: var(--accent);\n"
"        flex: 0 0 auto;\n"
"      }\n"
"\n"
"      .logo-lockup svg,\n"
"      .icon svg,\n"
"      .note-leaf svg,\n"
"      .led-leaf svg,\n"
"      .flower svg {\n"
"        display: block;\n"
"        width: 100%;\n"
"        height: 100%;\n"
"      }\n"
"\n"
"      .eyebrow,\n"
"      .meta-label,\n"
"      .card-label {\n"
"        font-family: var(--mono);\n"
"        font-size: 0.72rem;\n"
"        letter-spacing: 0.12em;\n"
"        text-transform: uppercase;\n"
"        color: var(--text-soft);\n"
"      }\n"
"\n"
"      .brand-copy {\n"
"        display: grid;\n"
"        gap: 8px;\n"
"        max-width: 640px;\n"
"      }\n"
"\n"
"      .brand-copy h1 {\n"
"        margin: 0;\n"
"        font-size: clamp(1.7rem, 2.8vw, 2.4rem);\n"
"        line-height: 1;\n"
"        letter-spacing: 0.04em;\n"
"        text-transform: uppercase;\n"
"      }\n"
"\n"
"      .brand-copy p {\n"
"        margin: 0;\n"
"        font-size: 0.98rem;\n"
"        line-height: 1.55;\n"
"        color: var(--text-soft);\n"
"      }\n"
"\n"
"      .header-actions {\n"
"        display: grid;\n"
"        gap: 12px;\n"
"        justify-items: end;\n"
"      }\n"
"\n"
"      .status-row,\n"
"      .mode-buttons {\n"
"        display: flex;\n"
"        align-items: center;\n"
"        gap: 10px;\n"
"        flex-wrap: wrap;\n"
"        justify-content: flex-end;\n"
"      }\n"
"\n"
"      .pill,\n"
"      .mode-chip {\n"
"        display: inline-flex;\n"
"        align-items: center;\n"
"        gap: 8px;\n"
"        min-height: 40px;\n"
"        padding: 0 14px;\n"
"        border-radius: 999px;\n"
"        border: 1px solid var(--edge);\n"
"        background: rgba(255, 255, 255, 0.78);\n"
"        box-shadow: var(--shadow-soft);\n"
"        font-family: var(--mono);\n"
"        font-size: 0.78rem;\n"
"      }\n"
"\n"
"      .pill strong {\n"
"        font-family: var(--display);\n"
"        font-size: 0.88rem;\n"
"      }\n"
"\n"
"      .pill.status-live {\n"
"        color: #ffffff;\n"
"        border-color: var(--accent);\n"
"        background: linear-gradient(145deg, #07905d, var(--accent));\n"
"      }\n"
"\n"
"      .pill.status-warn {\n"
"        border-color: rgba(212, 138, 0, 0.3);\n"
"        background: rgba(255, 245, 224, 0.92);\n"
"        color: #7a5a08;\n"
"      }\n"
"\n"
"      .pill.status-error {\n"
"        border-color: rgba(219, 93, 56, 0.28);\n"
"        background: rgba(255, 238, 233, 0.94);\n"
"        color: #8b3e24;\n"
"      }\n"
"\n"
"      .mode-button {\n"
"        width: 58px;\n"
"        height: 58px;\n"
"        display: inline-grid;\n"
"        place-items: center;\n"
"        border-radius: 50%;\n"
"        border: 1px solid var(--edge-strong);\n"
"        background: rgba(255, 255, 255, 0.8);\n"
"        box-shadow: var(--shadow-soft);\n"
"        color: var(--accent);\n"
"      }\n"
"\n"
"      .mode-button.pulse {\n"
"        border-width: 2px;\n"
"      }\n"
"\n"
"      .mode-button.pulse::after {\n"
"        content: \"\";\n"
"        position: absolute;\n"
"        inset: -6px;\n"
"        border-radius: inherit;\n"
"        border: 1px solid rgba(0, 131, 81, 0.16);\n"
"        animation: pulse-ring 2.2s ease-out infinite;\n"
"      }\n"
"\n"
"      .mode-button.muted {\n"
"        width: 46px;\n"
"        height: 46px;\n"
"        color: rgba(19, 49, 38, 0.5);\n"
"      }\n"
"\n"
"      @keyframes pulse-ring {\n"
"        0% {\n"
"          opacity: 0.6;\n"
"          transform: scale(0.95);\n"
"        }\n"
"\n"
"        100% {\n"
"          opacity: 0;\n"
"          transform: scale(1.18);\n"
"        }\n"
"      }\n"
"\n"
"      .icon {\n"
"        width: 24px;\n"
"        height: 24px;\n"
"      }\n"
"\n"
"      .dashboard {\n"
"        display: grid;\n"
"        grid-template-columns: minmax(0, 1.4fr) minmax(300px, 0.9fr);\n"
"        gap: clamp(16px, 1.8vw, 24px);\n"
"        align-items: start;\n"
"      }\n"
"\n"
"      .main-column,\n"
"      .side-column {\n"
"        display: grid;\n"
"        gap: 16px;\n"
"      }\n"
"\n"
"      .glass-panel {\n"
"        display: grid;\n"
"        gap: 14px;\n"
"        padding: 18px;\n"
"        border: 1px solid var(--edge);\n"
"        border-radius: var(--radius-lg);\n"
"        background:\n"
"          linear-gradient(145deg, rgba(255, 255, 255, 0.94), rgba(242, 248, 244, 0.78)),\n"
"          var(--panel-soft);\n"
"        box-shadow: var(--shadow-soft);\n"
"      }\n"
"\n"
"      .panel-head,\n"
"      .panel-head-inline {\n"
"        display: flex;\n"
"        justify-content: space-between;\n"
"        align-items: center;\n"
"        gap: 12px;\n"
"      }\n"
"\n"
"      .panel-title {\n"
"        margin: 0;\n"
"        font-size: 1.1rem;\n"
"        letter-spacing: 0.01em;\n"
"      }\n"
"\n"
"      .plant-wrap {\n"
"        display: grid;\n"
"        gap: 12px;\n"
"      }\n"
"\n"
"      .chart-frame {\n"
"        min-height: 260px;\n"
"        border: 2px solid rgba(93, 107, 98, 0.26);\n"
"        border-radius: 20px;\n"
"        background:\n"
"          linear-gradient(180deg, rgba(255, 255, 255, 0.96), rgba(246, 250, 247, 0.88));\n"
"        overflow: hidden;\n"
"      }\n"
"\n"
"      .chart-frame svg {\n"
"        display: block;\n"
"        width: 100%;\n"
"        height: 100%;\n"
"      }\n"
"\n"
"      .chart-stats {\n"
"        display: grid;\n"
"        grid-template-columns: repeat(3, minmax(0, 1fr));\n"
"        gap: 12px;\n"
"      }\n"
"\n"
"      .stat-card {\n"
"        padding: 14px;\n"
"        border-radius: var(--radius-md);\n"
"        border: 1px solid var(--edge);\n"
"        background: rgba(255, 255, 255, 0.74);\n"
"      }\n"
"\n"
"      .stat-value {\n"
"        margin-top: 6px;\n"
"        font-family: var(--mono);\n"
"        font-size: 1.05rem;\n"
"        color: var(--accent);\n"
"      }\n"
"\n"
"      .note-head {\n"
"        display: flex;\n"
"        justify-content: space-between;\n"
"        gap: 14px;\n"
"        align-items: baseline;\n"
"      }\n"
"\n"
"      .note-readout {\n"
"        font-family: var(--mono);\n"
"        font-size: clamp(0.98rem, 1.4vw, 1.12rem);\n"
"        color: var(--accent);\n"
"      }\n"
"\n"
"      .note-strip {\n"
"        display: grid;\n"
"        grid-template-columns: repeat(12, minmax(0, 1fr));\n"
"        gap: 8px;\n"
"      }\n"
"\n"
"      .note-cell {\n"
"        display: grid;\n"
"        justify-items: center;\n"
"        gap: 6px;\n"
"      }\n"
"\n"
"      .note-leaf {\n"
"        width: clamp(24px, 2.3vw, 32px);\n"
"        color: var(--muted);\n"
"        transition:\n"
"          color 140ms ease,\n"
"          transform 140ms ease;\n"
"      }\n"
"\n"
"      .note-cell.is-on .note-leaf {\n"
"        color: var(--accent);\n"
"        transform: translateY(-2px);\n"
"      }\n"
"\n"
"      .note-name {\n"
"        font-family: var(--mono);\n"
"        font-size: 0.72rem;\n"
"        color: var(--text-soft);\n"
"      }\n"
"\n"
"      .note-cell.is-on .note-name {\n"
"        color: var(--accent);\n"
"        font-weight: 700;\n"
"      }\n"
"\n"
"      .controls-grid {\n"
"        display: grid;\n"
"        grid-template-columns: repeat(2, minmax(0, 1fr));\n"
"        gap: 14px;\n"
"      }\n"
"\n"
"      .control-card {\n"
"        display: grid;\n"
"        gap: 10px;\n"
"        min-height: 132px;\n"
"        padding: 16px;\n"
"        border-radius: var(--radius-md);\n"
"        border: 1px solid var(--edge);\n"
"        background: rgba(255, 255, 255, 0.82);\n"
"      }\n"
"\n"
"      .control-card.is-featured {\n"
"        border-color: rgba(0, 131, 81, 0.22);\n"
"        background: linear-gradient(160deg, rgba(0, 131, 81, 0.06), rgba(255, 255, 255, 0.88));\n"
"      }\n"
"\n"
"      .control-label-row,\n"
"      .field-inline,\n"
"      .octave-row,\n"
"      .status-list,\n"
"      .segmented,\n"
"      .toggle-row,\n"
"      .drum-grid {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        flex-wrap: wrap;\n"
"      }\n"
"\n"
"      .control-label-row {\n"
"        justify-content: space-between;\n"
"        align-items: baseline;\n"
"      }\n"
"\n"
"      .control-name {\n"
"        font-family: var(--mono);\n"
"        font-size: 0.84rem;\n"
"        color: var(--text);\n"
"      }\n"
"\n"
"      .control-value {\n"
"        font-family: var(--mono);\n"
"        font-size: 0.88rem;\n"
"        color: var(--accent);\n"
"      }\n"
"\n"
"      .control-card input[type=\"range\"] {\n"
"        width: 100%;\n"
"        accent-color: var(--accent);\n"
"      }\n"
"\n"
"      .control-card select,\n"
"      .control-card input[type=\"number\"] {\n"
"        width: 100%;\n"
"        min-height: 42px;\n"
"        padding: 10px 12px;\n"
"        border-radius: 12px;\n"
"        border: 1px solid rgba(0, 131, 81, 0.18);\n"
"        background: rgba(248, 251, 249, 0.9);\n"
"        color: var(--text);\n"
"      }\n"
"\n"
"      .field-inline {\n"
"        align-items: center;\n"
"      }\n"
"\n"
"      .field-inline select,\n"
"      .field-inline input[type=\"number\"] {\n"
"        flex: 1 1 0;\n"
"        min-width: 0;\n"
"      }\n"
"\n"
"      .inline-chip {\n"
"        display: inline-flex;\n"
"        align-items: center;\n"
"        justify-content: center;\n"
"        min-width: 42px;\n"
"        min-height: 42px;\n"
"        padding: 0 12px;\n"
"        border-radius: 12px;\n"
"        border: 1px solid var(--edge);\n"
"        background: rgba(244, 248, 245, 0.86);\n"
"        font-family: var(--mono);\n"
"        font-size: 0.78rem;\n"
"      }\n"
"\n"
"      .segmented {\n"
"        align-items: center;\n"
"      }\n"
"\n"
"      .segmented button {\n"
"        flex: 1 1 0;\n"
"        min-height: 42px;\n"
"        padding: 0 12px;\n"
"        border-radius: 12px;\n"
"        border: 1px solid rgba(0, 131, 81, 0.16);\n"
"        background: rgba(244, 248, 245, 0.9);\n"
"        color: var(--text-soft);\n"
"        font-family: var(--mono);\n"
"      }\n"
"\n"
"      .segmented button.is-active {\n"
"        border-color: var(--accent);\n"
"        background: linear-gradient(145deg, #0b9461, var(--accent));\n"
"        color: #ffffff;\n"
"      }\n"
"\n"
"      .segmented button.is-disabled {\n"
"        opacity: 0.44;\n"
"      }\n"
"\n"
"      .toggle-button,\n"
"      .action-button {\n"
"        display: inline-flex;\n"
"        align-items: center;\n"
"        justify-content: center;\n"
"        min-height: 44px;\n"
"        padding: 0 14px;\n"
"        border-radius: 14px;\n"
"        border: 1px solid var(--edge);\n"
"        background: rgba(244, 248, 245, 0.92);\n"
"        color: var(--text);\n"
"      }\n"
"\n"
"      .toggle-button.is-active,\n"
"      .action-button.primary {\n"
"        border-color: var(--accent);\n"
"        background: linear-gradient(145deg, #0b9461, var(--accent));\n"
"        color: #ffffff;\n"
"      }\n"
"\n"
"      .toggle-button.warn {\n"
"        border-color: rgba(212, 138, 0, 0.32);\n"
"        color: #7a5a08;\n"
"      }\n"
"\n"
"      .panel-copy {\n"
"        margin: 0;\n"
"        color: var(--text-soft);\n"
"        line-height: 1.55;\n"
"      }\n"
"\n"
"      .led-preview {\n"
"        display: grid;\n"
"        grid-template-columns: auto 1fr;\n"
"        gap: 16px;\n"
"        align-items: stretch;\n"
"      }\n"
"\n"
"      .led-stack {\n"
"        display: grid;\n"
"        justify-items: center;\n"
"        gap: 10px;\n"
"        padding: 6px 0;\n"
"      }\n"
"\n"
"      .led-leaf {\n"
"        width: clamp(44px, 4vw, 58px);\n"
"        --leaf-orientation: scaleX(1);\n"
"        color: rgba(0, 200, 83, 0.24);\n"
"        transform: var(--leaf-orientation) scale(1);\n"
"        transform-origin: 50% 50%;\n"
"        transition:\n"
"          color 160ms ease,\n"
"          transform 160ms ease,\n"
"          filter 160ms ease;\n"
"      }\n"
"\n"
"      .led-leaf.is-on {\n"
"        transform: var(--leaf-orientation) scale(1.02);\n"
"        filter: drop-shadow(0 4px 12px rgba(0, 200, 83, 0.24));\n"
"      }\n"
"\n"
"      .led-leaf.is-hit {\n"
"        color: #00c49a;\n"
"      }\n"
"\n"
"      .led-summary {\n"
"        display: grid;\n"
"        gap: 12px;\n"
"        align-content: start;\n"
"      }\n"
"\n"
"      .status-list {\n"
"        row-gap: 8px;\n"
"      }\n"
"\n"
"      .status-chip {\n"
"        padding: 8px 12px;\n"
"        border-radius: 999px;\n"
"        background: rgba(240, 246, 242, 0.92);\n"
"        border: 1px solid var(--edge);\n"
"        font-family: var(--mono);\n"
"        font-size: 0.76rem;\n"
"      }\n"
"\n"
"      .output-card,\n"
"      .advanced-panel {\n"
"        display: grid;\n"
"        gap: 14px;\n"
"      }\n"
"\n"
"      .advanced-panel summary {\n"
"        display: flex;\n"
"        justify-content: space-between;\n"
"        align-items: center;\n"
"        list-style: none;\n"
"        cursor: pointer;\n"
"      }\n"
"\n"
"      .advanced-panel summary::-webkit-details-marker {\n"
"        display: none;\n"
"      }\n"
"\n"
"      .advanced-grid {\n"
"        display: grid;\n"
"        grid-template-columns: repeat(2, minmax(0, 1fr));\n"
"        gap: 14px;\n"
"      }\n"
"\n"
"      .drum-grid {\n"
"        display: grid;\n"
"        grid-template-columns: repeat(4, minmax(0, 1fr));\n"
"        gap: 10px;\n"
"      }\n"
"\n"
"      .drum-button {\n"
"        display: grid;\n"
"        gap: 6px;\n"
"        min-height: 72px;\n"
"        padding: 10px;\n"
"        border-radius: 14px;\n"
"        border: 1px solid var(--edge);\n"
"        background: rgba(245, 249, 246, 0.92);\n"
"        text-align: left;\n"
"      }\n"
"\n"
"      .drum-button.is-active {\n"
"        border-color: var(--accent);\n"
"        background: rgba(0, 131, 81, 0.08);\n"
"      }\n"
"\n"
"      .drum-button.is-hit {\n"
"        box-shadow: inset 0 0 0 2px rgba(0, 131, 81, 0.18);\n"
"      }\n"
"\n"
"      .drum-name {\n"
"        font-family: var(--mono);\n"
"        font-size: 0.78rem;\n"
"      }\n"
"\n"
"      .drum-state {\n"
"        font-size: 0.74rem;\n"
"        color: var(--text-soft);\n"
"      }\n"
"\n"
"      .flower-wrap {\n"
"        display: grid;\n"
"        place-items: center;\n"
"        padding: 8px 0 2px;\n"
"      }\n"
"\n"
"      .flower {\n"
"        width: min(190px, 56vw);\n"
"        color: var(--accent);\n"
"        opacity: 0.96;\n"
"      }\n"
"\n"
"      .footer-note {\n"
"        display: flex;\n"
"        justify-content: space-between;\n"
"        gap: 14px;\n"
"        align-items: center;\n"
"        flex-wrap: wrap;\n"
"        padding-top: 4px;\n"
"      }\n"
"\n"
"      .footer-note p {\n"
"        margin: 0;\n"
"        color: var(--text-soft);\n"
"      }\n"
"\n"
"      .banner {\n"
"        min-height: 20px;\n"
"        font-family: var(--mono);\n"
"        font-size: 0.8rem;\n"
"        color: var(--text-soft);\n"
"      }\n"
"\n"
"      .banner.ok {\n"
"        color: var(--accent-strong);\n"
"      }\n"
"\n"
"      .banner.warn {\n"
"        color: #8a6200;\n"
"      }\n"
"\n"
"      .banner.error {\n"
"        color: #944a2e;\n"
"      }\n"
"\n"
"      @media (max-width: 1120px) {\n"
"        .dashboard {\n"
"          grid-template-columns: 1fr;\n"
"        }\n"
"\n"
"        .side-column {\n"
"          grid-template-columns: repeat(2, minmax(0, 1fr));\n"
"          align-items: start;\n"
"        }\n"
"      }\n"
"\n"
"      @media (max-width: 840px) {\n"
"        .surface-header,\n"
"        .panel-head,\n"
"        .panel-head-inline,\n"
"        .note-head,\n"
"        .footer-note {\n"
"          flex-direction: column;\n"
"          align-items: flex-start;\n"
"        }\n"
"\n"
"        .header-actions {\n"
"          justify-items: start;\n"
"        }\n"
"\n"
"        .status-row,\n"
"        .mode-buttons {\n"
"          justify-content: flex-start;\n"
"        }\n"
"\n"
"        .controls-grid,\n"
"        .advanced-grid,\n"
"        .side-column {\n"
"          grid-template-columns: 1fr;\n"
"        }\n"
"\n"
"        .chart-stats {\n"
"          grid-template-columns: 1fr;\n"
"        }\n"
"\n"
"        .led-preview {\n"
"          grid-template-columns: 1fr;\n"
"        }\n"
"\n"
"        .led-stack {\n"
"          grid-template-columns: repeat(8, minmax(0, 1fr));\n"
"          grid-auto-flow: column;\n"
"        }\n"
"\n"
"        .drum-grid {\n"
"          grid-template-columns: repeat(2, minmax(0, 1fr));\n"
"        }\n"
"      }\n"
"\n"
"      @media (max-width: 620px) {\n"
"        .beca-app {\n"
"          padding: 10px;\n"
"        }\n"
"\n"
"        .surface {\n"
"          padding: 14px;\n"
"          border-radius: 22px;\n"
"        }\n"
"\n"
"        .brand-area {\n"
"          flex-direction: column;\n"
"        }\n"
"\n"
"        .note-strip {\n"
"          grid-template-columns: repeat(6, minmax(0, 1fr));\n"
"        }\n"
"\n"
"        .drum-grid {\n"
"          grid-template-columns: 1fr 1fr;\n"
"        }\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <main class=\"beca-app\">\n"
"      <section class=\"surface\">\n"
"        <header class=\"surface-header\">\n"
"          <div class=\"brand-area\">\n"
"            <div class=\"logo-lockup\" aria-hidden=\"true\">\n"
"              <svg viewBox=\"0 0 498 372\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
"                <path d=\"M397.017 323.145V137.412c0-2.944.935-4.876 2.805-5.795 2.244-1.104 6.358-1.656 12.342-1.656h70.689c5.984 0 9.911.552 11.781 1.656 2.244.919 3.366 2.851 3.366 5.795v185.733h-45.442v-55.747h-11.221v55.747h-44.32Zm44.32-173.866v98.524h11.221v-98.524h-11.221Z\" fill=\"currentColor\"/>\n"
"                <path d=\"M329.951 338.074h11.22V205.554h44.321v153.018c0 5.084-1.123 8.58-3.367 10.487-1.87 1.589-5.797 2.383-11.781 2.383h-70.688c-5.984 0-10.098-.794-12.342-2.383-1.87-1.907-2.805-5.403-2.805-10.487V50.63c0-5.085.935-8.422 2.805-10.011 2.244-1.907 6.358-2.86 12.342-2.86h70.688c5.984 0 9.911.953 11.781 2.86 2.244 1.589 3.367 4.926 3.367 10.011v145.39h-44.321V71.128h-11.22v266.946Z\" fill=\"currentColor\"/>\n"
"                <path d=\"M272.984 144.437v33.368h-55.541v122.51h11.22V187.816h44.321v145.867H172.001V0h100.983v134.903h-44.321V33.368h-11.22v111.069h55.541Z\" fill=\"currentColor\"/>\n"
"                <path d=\"M103.659 23.27v77.456h11.579V23.27h-11.579Zm0 100.726v85.434h11.579v-85.434h-11.579Zm45.16-13.297h-1.737v3.989h1.737c5.017 0 8.491.665 10.421 1.994 1.93 1.108 2.895 3.435 2.895 6.981v100.061c0 3.546-1.158 5.984-3.474 7.314-1.93 1.108-5.79 1.662-11.579 1.662H56.762V0h90.32c5.789 0 9.649.665 11.579 1.995 2.316 1.108 3.474 3.435 3.474 6.981v92.747c0 3.324-.965 5.651-2.895 6.981-1.93 1.33-5.404 1.995-10.421 1.995Z\" fill=\"currentColor\"/>\n"
"                <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24.588 195.819c-12.009 0-21.744-9.735-21.744-21.744V92.865C2.844 80.856 12.579 71.121 24.588 71.121c12.009 0 21.744 9.735 21.744 21.744v81.21c0 12.009-9.735 21.744-21.744 21.744Zm-14.224-21.744c0 7.856 6.368 14.225 14.224 14.225 7.856 0 14.224-6.369 14.224-14.225V92.865c0-7.856-6.368-14.224-14.224-14.224-7.856 0-14.224 6.368-14.224 14.224v81.21Z\" fill=\"currentColor\"/>\n"
"                <path d=\"M24.588 16.854c13.579 0 24.588 11.008 24.588 24.588 0 13.579-11.009 24.587-24.588 24.587C11.008 66.029 0 55.021 0 41.442 0 27.862 11.008 16.854 24.588 16.854Z\" fill=\"currentColor\"/>\n"
"              </svg>\n"
"            </div>\n"
"            <div class=\"brand-copy\">\n"
"              <span class=\"eyebrow\">Plant Music Interface</span>\n"
"              <h1>BECA Unified Control</h1>\n"
"              <p>\n"
"                One responsive surface for plant input, music generation, board LEDs, output\n"
"                routing, and synth shaping. Settings opens setup while the live controls stay here.\n"
"              </p>\n"
"            </div>\n"
"          </div>\n"
"\n"
"          <div class=\"header-actions\">\n"
"            <div class=\"status-row\">\n"
"              <div class=\"pill status-live\" id=\"connection-pill\">Connecting to BECA...</div>\n"
"              <div class=\"pill\" id=\"mode-pill\">Mode: --</div>\n"
"              <div class=\"pill\" id=\"output-pill\">Output: --</div>\n"
"            </div>\n"
"            <div class=\"mode-buttons\">\n"
"              <button class=\"mode-button pulse\" id=\"activity-button\" type=\"button\" aria-label=\"Live activity\">\n"
"                <span class=\"icon\" aria-hidden=\"true\">\n"
"                  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.1\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"                    <path d=\"M2 12h5l2.2-6 4.2 13 2.3-7H22\" />\n"
"                  </svg>\n"
"                </span>\n"
"              </button>\n"
"              <a class=\"mode-button muted\" id=\"settings-link\" href=\"/setup\" aria-label=\"Open setup\">\n"
"                <span class=\"icon\" aria-hidden=\"true\">\n"
"                  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.1\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"                    <circle cx=\"12\" cy=\"12\" r=\"3.1\" />\n"
"                    <path d=\"M19 12.8v-1.6l-1.8-.6a5.7 5.7 0 0 0-.5-1.2l.9-1.7-1.1-1.1-1.7.9a5.7 5.7 0 0 0-1.2-.5L13 5h-1.6l-.6 1.8a5.7 5.7 0 0 0-1.2.5l-1.7-.9-1.1 1.1.9 1.7a5.7 5.7 0 0 0-.5 1.2L5 11.2v1.6l1.8.6a5.7 5.7 0 0 0 .5 1.2l-.9 1.7 1.1 1.1 1.7-.9a5.7 5.7 0 0 0 1.2.5l.6 1.8H13l.6-1.8a5.7 5.7 0 0 0 1.2-.5l1.7.9 1.1-1.1-.9-1.7a5.7 5.7 0 0 0 .5-1.2z\" />\n"
"                  </svg>\n"
"                </span>\n"
"              </a>\n"
"            </div>\n"
"          </div>\n"
"        </header>\n"
"\n"
"        <div class=\"dashboard\">\n"
"          <div class=\"main-column\">\n"
"            <section class=\"glass-panel\">\n"
"              <div class=\"panel-head\">\n"
"                <div>\n"
"                  <div class=\"card-label\">Plant input</div>\n"
"                  <h2 class=\"panel-title\">Responsive live monitor</h2>\n"
"                </div>\n"
"                <div class=\"mode-chip\" id=\"scope-pill\">Signal 0.000</div>\n"
"              </div>\n"
"\n"
"              <div class=\"plant-wrap\">\n"
"                <div class=\"chart-frame\">\n"
"                  <svg id=\"scope-chart\" viewBox=\"0 0 900 280\" preserveAspectRatio=\"none\" aria-label=\"Plant input chart\"></svg>\n"
"                </div>\n"
"                <div class=\"chart-stats\">\n"
"                  <div class=\"stat-card\">\n"
"                    <div class=\"meta-label\">Current note</div>\n"
"                    <div class=\"stat-value\" id=\"last-note\">--</div>\n"
"                  </div>\n"
"                  <div class=\"stat-card\">\n"
"                    <div class=\"meta-label\">Velocity</div>\n"
"                    <div class=\"stat-value\" id=\"last-velocity\">--</div>\n"
"                  </div>\n"
"                  <div class=\"stat-card\">\n"
"                    <div class=\"meta-label\">Clock</div>\n"
"                    <div class=\"stat-value\" id=\"clock-status\">--</div>\n"
"                  </div>\n"
"                </div>\n"
"              </div>\n"
"            </section>\n"
"\n"
"            <section class=\"glass-panel\">\n"
"              <div class=\"note-head\">\n"
"                <div>\n"
"                  <div class=\"card-label\">Note or chord played</div>\n"
"                  <h2 class=\"panel-title\">Pitch activity</h2>\n"
"                </div>\n"
"                <div class=\"note-readout\" id=\"note-readout\">Waiting for notes...</div>\n"
"              </div>\n"
"              <div class=\"note-strip\" id=\"note-strip\" aria-label=\"Active note strip\"></div>\n"
"            </section>\n"
"\n"
"            <section class=\"controls-grid\">\n"
"              <article class=\"control-card is-featured\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">sensitivity</span>\n"
"                  <span class=\"control-value\" id=\"value-sens\">0.00</span>\n"
"                </div>\n"
"                <input id=\"control-sens\" type=\"range\" min=\"0\" max=\"0.5\" step=\"0.01\" />\n"
"                <p class=\"panel-copy\">Balance how strongly plant movement drives note energy.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">preset</span>\n"
"                  <span class=\"control-value\" id=\"value-mode\">--</span>\n"
"                </div>\n"
"                <select id=\"control-mode\"></select>\n"
"                <p class=\"panel-copy\">Switch between notes, arp, chords, and drums without leaving the live page.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">scale</span>\n"
"                  <span class=\"control-value\" id=\"value-scale\">--</span>\n"
"                </div>\n"
"                <select id=\"control-scale\"></select>\n"
"                <p class=\"panel-copy\">Keep harmony musical while the plant keeps moving.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">root note</span>\n"
"                  <span class=\"control-value\" id=\"value-root\">--</span>\n"
"                </div>\n"
"                <select id=\"control-root\"></select>\n"
"                <p class=\"panel-copy\">Pin the harmonic center for the current scale.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">tempo</span>\n"
"                  <span class=\"control-value\" id=\"value-bpm\">--</span>\n"
"                </div>\n"
"                <input id=\"control-bpm\" type=\"range\" min=\"20\" max=\"240\" step=\"5\" />\n"
"                <p class=\"panel-copy\">Move from slow ambient drift to punchier rhythmic motion.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">time sig</span>\n"
"                  <span class=\"control-value\" id=\"value-ts\">--</span>\n"
"                </div>\n"
"                <select id=\"control-ts\"></select>\n"
"                <p class=\"panel-copy\">Choose the grid the transport locks into.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">swing</span>\n"
"                  <span class=\"control-value\" id=\"value-swing\">0%</span>\n"
"                </div>\n"
"                <input id=\"control-swing\" type=\"range\" min=\"0\" max=\"60\" step=\"1\" />\n"
"                <p class=\"panel-copy\">Introduce groove without losing timing stability.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">rest chance</span>\n"
"                  <span class=\"control-value\" id=\"value-rest\">0%</span>\n"
"                </div>\n"
"                <input id=\"control-rest\" type=\"range\" min=\"0\" max=\"0.8\" step=\"0.01\" />\n"
"                <p class=\"panel-copy\">Create space in the phrases and let the board breathe.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">oct range</span>\n"
"                  <span class=\"control-value\" id=\"value-octave\">C1 - C8</span>\n"
"                </div>\n"
"                <div class=\"field-inline octave-row\">\n"
"                  <select id=\"control-lo\"></select>\n"
"                  <span class=\"inline-chip\">to</span>\n"
"                  <select id=\"control-hi\"></select>\n"
"                </div>\n"
"                <p class=\"panel-copy\">Keep pitch output inside the range that feels right for the performance.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">clock source</span>\n"
"                  <span class=\"control-value\" id=\"value-clock\">--</span>\n"
"                </div>\n"
"                <div class=\"segmented\" id=\"clock-group\"></div>\n"
"                <p class=\"panel-copy\">Use the internal transport or follow plant-triggered timing.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">no repeat</span>\n"
"                  <span class=\"control-value\" id=\"value-norep\">OFF</span>\n"
"                </div>\n"
"                <div class=\"toggle-row\">\n"
"                  <button class=\"toggle-button\" id=\"control-norep\" type=\"button\">Keep notes moving</button>\n"
"                </div>\n"
"                <p class=\"panel-copy\">Reduce repeated notes when you want more melodic variation.</p>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">system actions</span>\n"
"                  <span class=\"control-value\" id=\"value-random\">Ready</span>\n"
"                </div>\n"
"                <div class=\"toggle-row\">\n"
"                  <button class=\"action-button primary\" id=\"random-button\" type=\"button\">Randomize</button>\n"
"                  <button class=\"action-button\" id=\"refresh-button\" type=\"button\">Refresh</button>\n"
"                </div>\n"
"                <p class=\"panel-copy\">Shuffle the live rig or reload the page state without leaving the session.</p>\n"
"              </article>\n"
"            </section>\n"
"\n"
"            <details class=\"glass-panel advanced-panel\" open>\n"
"              <summary>\n"
"                <div>\n"
"                  <div class=\"card-label\">Aux synth and rhythm</div>\n"
"                  <h2 class=\"panel-title\">Advanced voice shaping</h2>\n"
"                </div>\n"
"                <div class=\"mode-chip\" id=\"aux-pill\">Aux status: --</div>\n"
"              </summary>\n"
"\n"
"              <div class=\"advanced-grid\">\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">synth preset</span>\n"
"                    <span class=\"control-value\" id=\"value-preset\">--</span>\n"
"                  </div>\n"
"                  <select id=\"control-preset\"></select>\n"
"                  <div class=\"toggle-row\">\n"
"                    <button class=\"action-button\" id=\"test-chord-button\" type=\"button\">Test aux chord</button>\n"
"                    <button class=\"action-button\" id=\"preset-reset-button\" type=\"button\">Reset preset</button>\n"
"                  </div>\n"
"                </article>\n"
"\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">master</span>\n"
"                    <span class=\"control-value\" id=\"value-master\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-master\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\" />\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">drive</span>\n"
"                    <span class=\"control-value\" id=\"value-drive\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-drive\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\" />\n"
"                </article>\n"
"\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">filter cutoff</span>\n"
"                    <span class=\"control-value\" id=\"value-cutoff\">0 hz</span>\n"
"                  </div>\n"
"                  <input id=\"control-cutoff\" type=\"range\" min=\"20\" max=\"18000\" step=\"10\" />\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">resonance</span>\n"
"                    <span class=\"control-value\" id=\"value-resonance\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-resonance\" type=\"range\" min=\"0.1\" max=\"10\" step=\"0.1\" />\n"
"                </article>\n"
"\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">attack</span>\n"
"                    <span class=\"control-value\" id=\"value-attack\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-attack\" type=\"range\" min=\"0\" max=\"5\" step=\"0.01\" />\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">release</span>\n"
"                    <span class=\"control-value\" id=\"value-release\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-release\" type=\"range\" min=\"0.01\" max=\"10\" step=\"0.01\" />\n"
"                </article>\n"
"\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">decay</span>\n"
"                    <span class=\"control-value\" id=\"value-decay\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-decay\" type=\"range\" min=\"0\" max=\"5\" step=\"0.01\" />\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">sustain</span>\n"
"                    <span class=\"control-value\" id=\"value-sustain\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-sustain\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\" />\n"
"                </article>\n"
"\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">delay mix</span>\n"
"                    <span class=\"control-value\" id=\"value-delay-mix\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-delay-mix\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\" />\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">delay feedback</span>\n"
"                    <span class=\"control-value\" id=\"value-delay-feedback\">0.00</span>\n"
"                  </div>\n"
"                  <input id=\"control-delay-feedback\" type=\"range\" min=\"0\" max=\"0.95\" step=\"0.01\" />\n"
"                </article>\n"
"\n"
"                <article class=\"control-card\">\n"
"                  <div class=\"control-label-row\">\n"
"                    <span class=\"control-name\">drum parts</span>\n"
"                    <span class=\"control-value\" id=\"value-drum-mask\">8 on</span>\n"
"                  </div>\n"
"                  <div class=\"drum-grid\" id=\"drum-grid\"></div>\n"
"                </article>\n"
"              </div>\n"
"            </details>\n"
"          </div>\n"
"\n"
"          <aside class=\"side-column\">\n"
"            <section class=\"glass-panel\">\n"
"              <div class=\"panel-head-inline\">\n"
"                <div>\n"
"                  <div class=\"card-label\">Board LEDs</div>\n"
"                  <h2 class=\"panel-title\">Linked LED surface</h2>\n"
"                </div>\n"
"                <div class=\"mode-chip\" id=\"led-pill\">LEDs idle</div>\n"
"              </div>\n"
"\n"
"              <div class=\"led-preview\">\n"
"                <div class=\"led-stack\" id=\"led-stack\" aria-label=\"LED mirror\"></div>\n"
"                <div class=\"led-summary\">\n"
"                  <div class=\"status-list\">\n"
"                    <div class=\"status-chip\" id=\"fx-chip\">Effect: --</div>\n"
"                    <div class=\"status-chip\" id=\"palette-chip\">Palette: --</div>\n"
"                    <div class=\"status-chip\" id=\"brightness-chip\">Brightness: --</div>\n"
"                    <div class=\"status-chip\" id=\"motion-chip\">Motion: --</div>\n"
"                  </div>\n"
"                  <p class=\"panel-copy\">\n"
"                    These controls drive the BECA board LEDs directly so the hardware look stays tied\n"
"                    to the music engine.\n"
"                  </p>\n"
"                </div>\n"
"              </div>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">effect</span>\n"
"                  <span class=\"control-value\" id=\"value-fx\">--</span>\n"
"                </div>\n"
"                <select id=\"control-fx\"></select>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">palette</span>\n"
"                  <span class=\"control-value\" id=\"value-pal\">--</span>\n"
"                </div>\n"
"                <select id=\"control-pal\"></select>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">brightness</span>\n"
"                  <span class=\"control-value\" id=\"value-bright\">--</span>\n"
"                </div>\n"
"                <input id=\"control-bright\" type=\"range\" min=\"10\" max=\"255\" step=\"1\" />\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">motion</span>\n"
"                  <span class=\"control-value\" id=\"value-vs\">--</span>\n"
"                </div>\n"
"                <input id=\"control-vs\" type=\"range\" min=\"0\" max=\"255\" step=\"1\" />\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">energy</span>\n"
"                  <span class=\"control-value\" id=\"value-vi\">--</span>\n"
"                </div>\n"
"                <input id=\"control-vi\" type=\"range\" min=\"0\" max=\"255\" step=\"1\" />\n"
"              </article>\n"
"            </section>\n"
"\n"
"            <section class=\"glass-panel output-card\">\n"
"              <div class=\"panel-head-inline\">\n"
"                <div>\n"
"                  <div class=\"card-label\">Routing and safety</div>\n"
"                  <h2 class=\"panel-title\">Output + sync</h2>\n"
"                </div>\n"
"              </div>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">output</span>\n"
"                  <span class=\"control-value\" id=\"value-output\">--</span>\n"
"                </div>\n"
"                <div class=\"segmented\" id=\"output-group\"></div>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">DAW sync</span>\n"
"                  <span class=\"control-value\" id=\"value-sync\">OFF</span>\n"
"                </div>\n"
"                <div class=\"toggle-row\">\n"
"                  <button class=\"toggle-button\" id=\"sync-button\" type=\"button\">Toggle sync</button>\n"
"                </div>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">I/O mute</span>\n"
"                  <span class=\"control-value\" id=\"value-mute\">OFF</span>\n"
"                </div>\n"
"                <div class=\"toggle-row\">\n"
"                  <button class=\"toggle-button warn\" id=\"mute-button\" type=\"button\">Mute outputs</button>\n"
"                </div>\n"
"              </article>\n"
"\n"
"              <article class=\"control-card\">\n"
"                <div class=\"control-label-row\">\n"
"                  <span class=\"control-name\">runtime state</span>\n"
"                  <span class=\"control-value\" id=\"value-runtime\">steady</span>\n"
"                </div>\n"
"                <div class=\"status-list\">\n"
"                  <div class=\"status-chip\" id=\"transport-chip\">Transport: --</div>\n"
"                  <div class=\"status-chip\" id=\"sync-lock-chip\">Sync lock: --</div>\n"
"                  <div class=\"status-chip\" id=\"aux-ready-chip\">Aux: --</div>\n"
"                </div>\n"
"              </article>\n"
"            </section>\n"
"\n"
"            <section class=\"glass-panel\">\n"
"              <div class=\"panel-head-inline\">\n"
"                <div>\n"
"                  <div class=\"card-label\">Board identity</div>\n"
"                  <h2 class=\"panel-title\">Session summary</h2>\n"
"                </div>\n"
"              </div>\n"
"              <p class=\"panel-copy\" id=\"summary-copy\">\n"
"                Waiting for the current BECA state so the desktop app and browser board view stay in sync.\n"
"              </p>\n"
"              <div class=\"flower-wrap\" aria-hidden=\"true\">\n"
"                <div class=\"flower\">\n"
"                  <svg viewBox=\"0 0 525 513\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
"                    <path d=\"M320.693 210.915C503.433 -70.305 21.113 -70.305 203.853 210.915C21.113 -70.305 -127.947 388.415 167.743 322.035C-127.947 388.415 262.263 671.935 262.263 390.715C262.263 671.935 652.483 388.415 356.783 322.035C652.473 388.415 503.423 -70.305 320.673 210.915H320.693ZM262.273 356.985C182.593 466.305 118.003 401.705 227.323 322.035C118.003 242.355 182.593 177.775 262.273 287.095C341.953 177.775 406.543 242.355 297.223 322.035C406.543 401.705 341.953 466.305 262.273 356.985Z\" fill=\"currentColor\"/>\n"
"                  </svg>\n"
"                </div>\n"
"              </div>\n"
"            </section>\n"
"          </aside>\n"
"        </div>\n"
"\n"
"        <div class=\"footer-note\">\n"
"          <p>Settings opens setup. The rest of the board stays controllable from this page.</p>\n"
"          <div class=\"banner\" id=\"banner\">Loading live state…</div>\n"
"        </div>\n"
"      </section>\n"
"    </main>\n"
"\n"
"    <script>\n"
"      (() => {\n"
"        const NOTE_NAMES = [\"C\", \"C#\", \"D\", \"D#\", \"E\", \"F\", \"F#\", \"G\", \"G#\", \"A\", \"A#\", \"B\"];\n"
"        const OUTPUT_LABELS = [\"BLE\", \"SERIAL\", \"AUX OUT\"];\n"
"        const CLOCK_LABELS = [\"Internal\", \"Plant\"];\n"
"        const LED_SLOT_COUNT = 8;\n"
"        const LED_DISPLAY_SETTING = 0;\n"
"        const LED_DISPLAY_VOLUME = 1;\n"
"        const LED_DISPLAY_OUTPUT = 2;\n"
"        const LED_DISPLAY_RANDOM = 3;\n"
"        const LED_OFF_COLOR = \"rgba(0, 200, 83, 0.24)\";\n"
"        const CONTROL_INPUT_COMMIT_MS = 85;\n"
"        const METER_COLORS = [\"#00c853\", \"#00c853\", \"#7fd900\", \"#d8df00\", \"#ffd400\", \"#ff9f00\", \"#ff5a00\", \"#f12129\"];\n"
"        const SETTING_COLORS = [\n"
"          \"#00c853\",\n"
"          \"#ffd400\",\n"
"          \"#ff5a00\",\n"
"          \"#00c8ff\",\n"
"          \"#f12129\",\n"
"          \"#6e2cff\",\n"
"          \"#ed29ac\",\n"
"          \"#ffffff\",\n"
"          \"#ffffff\",\n"
"          \"#00c49a\",\n"
"          \"#124cec\",\n"
"          \"#00bf45\",\n"
"          \"#ff9f00\"\n"
"        ];\n"
"        const OUTPUT_PATTERNS = [\n"
"          [\"#00c8ff\", null, \"#00c8ff\", null, \"#00c8ff\", null, \"#00c8ff\", null],\n"
"          [\"#6e2cff\", \"#00c49a\", \"#00c853\", \"#00c853\", \"#ffd400\", \"#ffd400\", \"#ff5a00\", \"#f12129\"],\n"
"          [\"#00c853\", \"#00c853\", null, null, null, null, null, null]\n"
"        ];\n"
"        const RANDOM_PATTERN = [\"#6e2cff\", null, \"#00c853\", null, \"#ffd400\", null, \"#ff5a00\", null];\n"
"        const DRUM_PARTS = [\n"
"          { bit: 0, label: \"Kick\" },\n"
"          { bit: 1, label: \"Snare\" },\n"
"          { bit: 2, label: \"Closed HH\" },\n"
"          { bit: 3, label: \"Open HH\" },\n"
"          { bit: 4, label: \"Tom 1\" },\n"
"          { bit: 5, label: \"Tom 2\" },\n"
"          { bit: 6, label: \"Ride\" },\n"
"          { bit: 7, label: \"Crash\" }\n"
"        ];\n"
"\n"
"        const state = {\n"
"          params: null,\n"
"          effects: [],\n"
"          palettes: [],\n"
"          runtime: null,\n"
"          synth: null,\n"
"          noteList: [],\n"
"          noteVelocity: 0,\n"
"          drumMask: 0,\n"
"          drumHitMask: 0,\n"
"          plantPoints: Array.from({ length: 42 }, () => 0),\n"
"          scopeValue: 0,\n"
"          syncLocked: false,\n"
"          auxReady: true,\n"
"          pendingControlPosts: new Map(),\n"
"          pendingControlTimer: null\n"
"        };\n"
"\n"
"        const el = {\n"
"          banner: document.querySelector(\"#banner\"),\n"
"          connectionPill: document.querySelector(\"#connection-pill\"),\n"
"          modePill: document.querySelector(\"#mode-pill\"),\n"
"          outputPill: document.querySelector(\"#output-pill\"),\n"
"          scopePill: document.querySelector(\"#scope-pill\"),\n"
"          chart: document.querySelector(\"#scope-chart\"),\n"
"          lastNote: document.querySelector(\"#last-note\"),\n"
"          lastVelocity: document.querySelector(\"#last-velocity\"),\n"
"          clockStatus: document.querySelector(\"#clock-status\"),\n"
"          noteReadout: document.querySelector(\"#note-readout\"),\n"
"          noteStrip: document.querySelector(\"#note-strip\"),\n"
"          outputGroup: document.querySelector(\"#output-group\"),\n"
"          clockGroup: document.querySelector(\"#clock-group\"),\n"
"          ledStack: document.querySelector(\"#led-stack\"),\n"
"          drumGrid: document.querySelector(\"#drum-grid\"),\n"
"          syncButton: document.querySelector(\"#sync-button\"),\n"
"          muteButton: document.querySelector(\"#mute-button\"),\n"
"          norepButton: document.querySelector(\"#control-norep\"),\n"
"          randomButton: document.querySelector(\"#random-button\"),\n"
"          refreshButton: document.querySelector(\"#refresh-button\"),\n"
"          testChordButton: document.querySelector(\"#test-chord-button\"),\n"
"          presetResetButton: document.querySelector(\"#preset-reset-button\"),\n"
"          auxPill: document.querySelector(\"#aux-pill\"),\n"
"          ledPill: document.querySelector(\"#led-pill\"),\n"
"          fxChip: document.querySelector(\"#fx-chip\"),\n"
"          paletteChip: document.querySelector(\"#palette-chip\"),\n"
"          brightnessChip: document.querySelector(\"#brightness-chip\"),\n"
"          motionChip: document.querySelector(\"#motion-chip\"),\n"
"          transportChip: document.querySelector(\"#transport-chip\"),\n"
"          syncLockChip: document.querySelector(\"#sync-lock-chip\"),\n"
"          auxReadyChip: document.querySelector(\"#aux-ready-chip\"),\n"
"          summaryCopy: document.querySelector(\"#summary-copy\"),\n"
"          valueMode: document.querySelector(\"#value-mode\"),\n"
"          valueScale: document.querySelector(\"#value-scale\"),\n"
"          valueRoot: document.querySelector(\"#value-root\"),\n"
"          valueBpm: document.querySelector(\"#value-bpm\"),\n"
"          valueTs: document.querySelector(\"#value-ts\"),\n"
"          valueSwing: document.querySelector(\"#value-swing\"),\n"
"          valueRest: document.querySelector(\"#value-rest\"),\n"
"          valueSens: document.querySelector(\"#value-sens\"),\n"
"          valueOctave: document.querySelector(\"#value-octave\"),\n"
"          valueClock: document.querySelector(\"#value-clock\"),\n"
"          valueNoRep: document.querySelector(\"#value-norep\"),\n"
"          valueRandom: document.querySelector(\"#value-random\"),\n"
"          valuePreset: document.querySelector(\"#value-preset\"),\n"
"          valueMaster: document.querySelector(\"#value-master\"),\n"
"          valueDrive: document.querySelector(\"#value-drive\"),\n"
"          valueCutoff: document.querySelector(\"#value-cutoff\"),\n"
"          valueResonance: document.querySelector(\"#value-resonance\"),\n"
"          valueAttack: document.querySelector(\"#value-attack\"),\n"
"          valueRelease: document.querySelector(\"#value-release\"),\n"
"          valueDecay: document.querySelector(\"#value-decay\"),\n"
"          valueSustain: document.querySelector(\"#value-sustain\"),\n"
"          valueDelayMix: document.querySelector(\"#value-delay-mix\"),\n"
"          valueDelayFeedback: document.querySelector(\"#value-delay-feedback\"),\n"
"          valueDrumMask: document.querySelector(\"#value-drum-mask\"),\n"
"          valueFx: document.querySelector(\"#value-fx\"),\n"
"          valuePal: document.querySelector(\"#value-pal\"),\n"
"          valueBright: document.querySelector(\"#value-bright\"),\n"
"          valueVs: document.querySelector(\"#value-vs\"),\n"
"          valueVi: document.querySelector(\"#value-vi\"),\n"
"          valueOutput: document.querySelector(\"#value-output\"),\n"
"          valueSync: document.querySelector(\"#value-sync\"),\n"
"          valueMute: document.querySelector(\"#value-mute\"),\n"
"          valueRuntime: document.querySelector(\"#value-runtime\"),\n"
"          controlMode: document.querySelector(\"#control-mode\"),\n"
"          controlScale: document.querySelector(\"#control-scale\"),\n"
"          controlRoot: document.querySelector(\"#control-root\"),\n"
"          controlTs: document.querySelector(\"#control-ts\"),\n"
"          controlLo: document.querySelector(\"#control-lo\"),\n"
"          controlHi: document.querySelector(\"#control-hi\"),\n"
"          controlPreset: document.querySelector(\"#control-preset\"),\n"
"          controlFx: document.querySelector(\"#control-fx\"),\n"
"          controlPal: document.querySelector(\"#control-pal\"),\n"
"          controlBpm: document.querySelector(\"#control-bpm\"),\n"
"          controlSwing: document.querySelector(\"#control-swing\"),\n"
"          controlRest: document.querySelector(\"#control-rest\"),\n"
"          controlSens: document.querySelector(\"#control-sens\"),\n"
"          controlBright: document.querySelector(\"#control-bright\"),\n"
"          controlVs: document.querySelector(\"#control-vs\"),\n"
"          controlVi: document.querySelector(\"#control-vi\"),\n"
"          controlMaster: document.querySelector(\"#control-master\"),\n"
"          controlDrive: document.querySelector(\"#control-drive\"),\n"
"          controlCutoff: document.querySelector(\"#control-cutoff\"),\n"
"          controlResonance: document.querySelector(\"#control-resonance\"),\n"
"          controlAttack: document.querySelector(\"#control-attack\"),\n"
"          controlRelease: document.querySelector(\"#control-release\"),\n"
"          controlDecay: document.querySelector(\"#control-decay\"),\n"
"          controlSustain: document.querySelector(\"#control-sustain\"),\n"
"          controlDelayMix: document.querySelector(\"#control-delay-mix\"),\n"
"          controlDelayFeedback: document.querySelector(\"#control-delay-feedback\")\n"
"        };\n"
"\n"
"        function noteLeafSvg() {\n"
"          return `\n"
"            <svg viewBox=\"0 0 100 100\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
"              <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M100 48.864C100 77.106 77.106 100 48.864 100H0V51.136C0 22.894 22.894 0 51.136 0H100v48.864ZM51.136 11.364c-21.965 0-39.772 17.807-39.772 39.772V81.17l42.005-42.005c2.219-2.219 5.817-2.219 8.036 0 2.219 2.219 2.219 5.817 0 8.036L19.967 88.636h28.897c21.965 0 39.772-17.807 39.772-39.772V11.364H51.136Z\" fill=\"currentColor\"/>\n"
"            </svg>\n"
"          `;\n"
"        }\n"
"\n"
"        function setBanner(message, tone = \"\") {\n"
"          el.banner.textContent = message;\n"
"          el.banner.className = \"banner\";\n"
"          if (tone) el.banner.classList.add(tone);\n"
"        }\n"
"\n"
"        function setConnection(message, tone = \"status-live\") {\n"
"          el.connectionPill.textContent = message;\n"
"          el.connectionPill.className = `pill ${tone}`;\n"
"        }\n"
"\n"
"        function fmtNumber(value, digits = 2) {\n"
"          const n = Number(value);\n"
"          if (!Number.isFinite(n)) return \"--\";\n"
"          return n.toFixed(digits);\n"
"        }\n"
"\n"
"        function fmtPercent(value) {\n"
"          const n = Number(value);\n"
"          if (!Number.isFinite(n)) return \"--\";\n"
"          return `${Math.round(n * 100)}%`;\n"
"        }\n"
"\n"
"        function noteNameFromMidi(midi) {\n"
"          if (!Number.isFinite(midi)) return \"--\";\n"
"          const pc = ((midi % 12) + 12) % 12;\n"
"          const oct = Math.floor(midi / 12) - 1;\n"
"          return `${NOTE_NAMES[pc]}${oct}`;\n"
"        }\n"
"\n"
"        function noteNamesFromList(list) {\n"
"          return list.map((midi) => noteNameFromMidi(midi).toLowerCase());\n"
"        }\n"
"\n"
"        function inferChord(list) {\n"
"          if (!Array.isArray(list) || list.length < 3) return \"\";\n"
"          const pcs = [...new Set(list.map((value) => ((value % 12) + 12) % 12))];\n"
"          if (pcs.length < 3) return \"\";\n"
"          for (const root of pcs) {\n"
"            const rel = pcs\n"
"              .map((pc) => (pc - root + 12) % 12)\n"
"              .sort((a, b) => a - b)\n"
"              .join(\",\");\n"
"            if (rel.includes(\"0,4,7\")) return `${NOTE_NAMES[root].toLowerCase()}maj`;\n"
"            if (rel.includes(\"0,3,7\")) return `${NOTE_NAMES[root].toLowerCase()}min`;\n"
"            if (rel.includes(\"0,4,7,11\")) return `${NOTE_NAMES[root].toLowerCase()}maj7`;\n"
"            if (rel.includes(\"0,3,7,10\")) return `${NOTE_NAMES[root].toLowerCase()}min7`;\n"
"            if (rel.includes(\"0,5,7\")) return `${NOTE_NAMES[root].toLowerCase()}sus4`;\n"
"            if (rel.includes(\"0,2,7\")) return `${NOTE_NAMES[root].toLowerCase()}sus2`;\n"
"          }\n"
"          return \"\";\n"
"        }\n"
"\n"
"        function addPlantPoint(value) {\n"
"          const next = Math.max(0, Math.min(1, Number(value) || 0));\n"
"          state.scopeValue = next;\n"
"          state.plantPoints.push(next);\n"
"          if (state.plantPoints.length > 42) state.plantPoints.shift();\n"
"          renderChart();\n"
"        }\n"
"\n"
"        function renderChart() {\n"
"          const width = 900;\n"
"          const height = 280;\n"
"          const baseline = height - 44;\n"
"          const points = state.plantPoints\n"
"            .map((value, index) => {\n"
"              const x = (index / Math.max(1, state.plantPoints.length - 1)) * width;\n"
"              const y = baseline - value * 144;\n"
"              return `${x.toFixed(2)},${y.toFixed(2)}`;\n"
"            })\n"
"            .join(\" \");\n"
"\n"
"          const areaPoints = `0,${baseline} ${points} ${width},${baseline}`;\n"
"          el.chart.innerHTML = `\n"
"            <defs>\n"
"              <linearGradient id=\"line-gradient\" x1=\"0\" x2=\"1\" y1=\"0\" y2=\"0\">\n"
"                <stop offset=\"0%\" stop-color=\"#008351\" />\n"
"                <stop offset=\"100%\" stop-color=\"#88c439\" />\n"
"              </linearGradient>\n"
"              <linearGradient id=\"fill-gradient\" x1=\"0\" x2=\"0\" y1=\"0\" y2=\"1\">\n"
"                <stop offset=\"0%\" stop-color=\"rgba(0,131,81,0.22)\" />\n"
"                <stop offset=\"100%\" stop-color=\"rgba(0,131,81,0.02)\" />\n"
"              </linearGradient>\n"
"            </defs>\n"
"            <rect x=\"0\" y=\"0\" width=\"${width}\" height=\"${height}\" fill=\"#ffffff\" />\n"
"            <g opacity=\"0.24\" stroke=\"#a9b8ae\" stroke-width=\"1\">\n"
"              <line x1=\"0\" x2=\"${width}\" y1=\"52\" y2=\"52\" />\n"
"              <line x1=\"0\" x2=\"${width}\" y1=\"104\" y2=\"104\" />\n"
"              <line x1=\"0\" x2=\"${width}\" y1=\"156\" y2=\"156\" />\n"
"              <line x1=\"0\" x2=\"${width}\" y1=\"208\" y2=\"208\" />\n"
"            </g>\n"
"            <polygon points=\"${areaPoints}\" fill=\"url(#fill-gradient)\" />\n"
"            <polyline\n"
"              points=\"${points}\"\n"
"              fill=\"none\"\n"
"              stroke=\"url(#line-gradient)\"\n"
"              stroke-width=\"5\"\n"
"              stroke-linecap=\"round\"\n"
"              stroke-linejoin=\"round\"\n"
"            />\n"
"          `;\n"
"          el.scopePill.textContent = `Signal ${fmtNumber(state.scopeValue, 3)}`;\n"
"        }\n"
"\n"
"        function renderNoteStrip() {\n"
"          el.noteStrip.innerHTML = \"\";\n"
"          const pcs = new Set(state.noteList.map((midi) => ((midi % 12) + 12) % 12));\n"
"          NOTE_NAMES.forEach((name, index) => {\n"
"            const cell = document.createElement(\"div\");\n"
"            cell.className = \"note-cell\";\n"
"            if (pcs.has(index)) cell.classList.add(\"is-on\");\n"
"            const leaf = document.createElement(\"span\");\n"
"            leaf.className = \"note-leaf\";\n"
"            leaf.innerHTML = noteLeafSvg();\n"
"            const label = document.createElement(\"span\");\n"
"            label.className = \"note-name\";\n"
"            label.textContent = name;\n"
"            cell.append(leaf, label);\n"
"            el.noteStrip.appendChild(cell);\n"
"          });\n"
"        }\n"
"\n"
"        function clamp(value, min, max) {\n"
"          return Math.max(min, Math.min(max, Number(value) || 0));\n"
"        }\n"
"\n"
"        function buildLedPattern() {\n"
"          const runtime = state.runtime || {};\n"
"          const fallbackCount = Math.max(\n"
"            1,\n"
"            Math.round((((runtime.vi || 0) / 255) * 0.55 + state.scopeValue * 0.45) * LED_SLOT_COUNT)\n"
"          );\n"
"          const displayMode = clamp(runtime.led_display_mode, LED_DISPLAY_SETTING, LED_DISPLAY_RANDOM);\n"
"\n"
"          if (displayMode === LED_DISPLAY_VOLUME) {\n"
"            const onCount = clamp(runtime.encoder_led_count || Math.round((state.synth?.master || 0.25) * LED_SLOT_COUNT), 1, LED_SLOT_COUNT);\n"
"            return Array.from({ length: LED_SLOT_COUNT }, (_, slot) => ({\n"
"              color: METER_COLORS[Math.min(slot, METER_COLORS.length - 1)],\n"
"              on: slot < onCount\n"
"            }));\n"
"          }\n"
"\n"
"          if (displayMode === LED_DISPLAY_OUTPUT) {\n"
"            const pattern = OUTPUT_PATTERNS[clamp(runtime.outputmode, 0, OUTPUT_PATTERNS.length - 1)] || OUTPUT_PATTERNS[0];\n"
"            return pattern.map((color) => ({ color: color || LED_OFF_COLOR, on: Boolean(color) }));\n"
"          }\n"
"\n"
"          if (displayMode === LED_DISPLAY_RANDOM) {\n"
"            return RANDOM_PATTERN.map((color) => ({ color: color || LED_OFF_COLOR, on: Boolean(color) }));\n"
"          }\n"
"\n"
"          const setting = clamp(runtime.encoder_setting, 0, SETTING_COLORS.length - 1);\n"
"          const color = SETTING_COLORS[setting] || SETTING_COLORS[0];\n"
"          if (setting === 4) {\n"
"            const bpm = clamp(runtime.bpm || 120, 20, 240);\n"
"            const beatMs = Math.max(120, 60000 / bpm);\n"
"            const activeSlot = Math.floor(performance.now() / beatMs) % LED_SLOT_COUNT;\n"
"            return Array.from({ length: LED_SLOT_COUNT }, (_, slot) => ({ color, on: slot === activeSlot }));\n"
"          }\n"
"          if (setting === 7 || setting === 8) {\n"
"            const lo = clamp(runtime.lo || 1, 1, LED_SLOT_COUNT);\n"
"            const hi = clamp(runtime.hi || lo, lo, LED_SLOT_COUNT);\n"
"            return Array.from({ length: LED_SLOT_COUNT }, (_, slot) => ({\n"
"              color,\n"
"              on: slot + 1 >= lo && slot + 1 <= hi\n"
"            }));\n"
"          }\n"
"\n"
"          const onCount = clamp(runtime.encoder_led_count || fallbackCount, 1, LED_SLOT_COUNT);\n"
"          return Array.from({ length: LED_SLOT_COUNT }, (_, slot) => ({ color, on: slot < onCount }));\n"
"        }\n"
"\n"
"        function renderLedStack() {\n"
"          const pattern = buildLedPattern();\n"
"          el.ledStack.innerHTML = \"\";\n"
"          for (let visual = LED_SLOT_COUNT - 1; visual >= 0; visual -= 1) {\n"
"            const leaf = document.createElement(\"div\");\n"
"            leaf.className = \"led-leaf\";\n"
"            const topIndex = LED_SLOT_COUNT - 1 - visual;\n"
"            leaf.style.setProperty(\"--leaf-orientation\", topIndex % 2 === 0 ? \"scaleX(1)\" : \"scaleX(-1)\");\n"
"            leaf.style.color = pattern[visual]?.on ? pattern[visual].color : LED_OFF_COLOR;\n"
"            if (pattern[visual]?.on) leaf.classList.add(\"is-on\");\n"
"            if (((state.drumHitMask >> visual) & 1) === 1) leaf.classList.add(\"is-hit\");\n"
"            leaf.innerHTML = noteLeafSvg();\n"
"            el.ledStack.appendChild(leaf);\n"
"          }\n"
"        }\n"
"\n"
"        function renderDrumGrid() {\n"
"          el.drumGrid.innerHTML = \"\";\n"
"          let enabledCount = 0;\n"
"          DRUM_PARTS.forEach((part) => {\n"
"            const active = ((state.drumMask >> part.bit) & 1) === 1;\n"
"            const hit = ((state.drumHitMask >> part.bit) & 1) === 1;\n"
"            if (active) enabledCount += 1;\n"
"            const button = document.createElement(\"button\");\n"
"            button.type = \"button\";\n"
"            button.className = \"drum-button\";\n"
"            if (active) button.classList.add(\"is-active\");\n"
"            if (hit) button.classList.add(\"is-hit\");\n"
"            button.innerHTML = `\n"
"              <span class=\"drum-name\">${part.label}</span>\n"
"              <span class=\"drum-state\">${active ? \"enabled\" : \"muted\"}</span>\n"
"            `;\n"
"            button.addEventListener(\"click\", async () => {\n"
"              const nextMask = active ? state.drumMask & ~(1 << part.bit) : state.drumMask | (1 << part.bit);\n"
"              await postSet(\"drumsel\", nextMask);\n"
"            });\n"
"            el.drumGrid.appendChild(button);\n"
"          });\n"
"          el.valueDrumMask.textContent = `${enabledCount} on`;\n"
"        }\n"
"\n"
"        function fillSelect(select, values, labeler) {\n"
"          select.innerHTML = \"\";\n"
"          values.forEach((value, index) => {\n"
"            const option = document.createElement(\"option\");\n"
"            option.value = String(index);\n"
"            option.textContent = labeler ? labeler(value, index) : String(value);\n"
"            select.appendChild(option);\n"
"          });\n"
"        }\n"
"\n"
"        function fillSelectFromValues(select, values) {\n"
"          select.innerHTML = \"\";\n"
"          values.forEach((value) => {\n"
"            const option = document.createElement(\"option\");\n"
"            option.value = String(value);\n"
"            option.textContent = String(value);\n"
"            select.appendChild(option);\n"
"          });\n"
"        }\n"
"\n"
"        function buildSegmented(container, items, onSelect) {\n"
"          container.innerHTML = \"\";\n"
"          items.forEach((item) => {\n"
"            const button = document.createElement(\"button\");\n"
"            button.type = \"button\";\n"
"            button.dataset.value = String(item.value);\n"
"            button.textContent = item.label;\n"
"            button.addEventListener(\"click\", () => {\n"
"              if (button.classList.contains(\"is-disabled\")) return;\n"
"              onSelect(item.value);\n"
"            });\n"
"            container.appendChild(button);\n"
"          });\n"
"        }\n"
"\n"
"        function updateSegmented(container, activeValue, disabledValue = null) {\n"
"          Array.from(container.children).forEach((button) => {\n"
"            const value = button.dataset.value;\n"
"            button.classList.toggle(\"is-active\", value === String(activeValue));\n"
"            button.classList.toggle(\"is-disabled\", disabledValue !== null && value === String(disabledValue));\n"
"          });\n"
"        }\n"
"\n"
"        function queuePostSet(key, value) {\n"
"          state.pendingControlPosts.set(key, value);\n"
"          if (state.pendingControlTimer !== null) return;\n"
"          state.pendingControlTimer = window.setTimeout(flushPendingPostSets, CONTROL_INPUT_COMMIT_MS);\n"
"        }\n"
"\n"
"        async function flushPendingPostSets() {\n"
"          const entries = Array.from(state.pendingControlPosts.entries());\n"
"          state.pendingControlPosts.clear();\n"
"          state.pendingControlTimer = null;\n"
"          for (const [key, value] of entries) {\n"
"            try {\n"
"              await postSet(key, value, { quiet: true });\n"
"            } catch (error) {}\n"
"          }\n"
"          if (state.pendingControlPosts.size > 0 && state.pendingControlTimer === null) {\n"
"            state.pendingControlTimer = window.setTimeout(flushPendingPostSets, CONTROL_INPUT_COMMIT_MS);\n"
"          }\n"
"        }\n"
"\n"
"        async function commitPostSet(key, value) {\n"
"          state.pendingControlPosts.delete(key);\n"
"          await postSet(key, value);\n"
"        }\n"
"\n"
"        function bindRange(input, key, formatter, sink) {\n"
"          input.addEventListener(\"input\", () => {\n"
"            const next = formatter(input.value);\n"
"            sink(next);\n"
"            queuePostSet(key, next);\n"
"          });\n"
"          input.addEventListener(\"change\", () => commitPostSet(key, formatter(input.value)));\n"
"        }\n"
"\n"
"        function bindPreview(input, formatter, sink) {\n"
"          input.addEventListener(\"input\", () => sink(formatter(input.value)));\n"
"        }\n"
"\n"
"        async function getJson(path) {\n"
"          const response = await fetch(path, { cache: \"no-store\" });\n"
"          if (!response.ok) throw new Error(`${path} returned ${response.status}`);\n"
"          return response.json();\n"
"        }\n"
"\n"
"        async function postForm(path, form) {\n"
"          const body = new URLSearchParams();\n"
"          Object.entries(form).forEach(([key, value]) => body.set(key, String(value)));\n"
"          const response = await fetch(path, { method: \"POST\", body });\n"
"          if (!response.ok) {\n"
"            let message = `${path} returned ${response.status}`;\n"
"            try {\n"
"              const payload = await response.json();\n"
"              if (payload && payload.err) message = payload.err;\n"
"            } catch (error) {}\n"
"            throw new Error(message);\n"
"          }\n"
"          const type = response.headers.get(\"Content-Type\") || \"\";\n"
"          return type.includes(\"application/json\") ? response.json() : response.text();\n"
"        }\n"
"\n"
"        async function postSet(key, value, options = {}) {\n"
"          try {\n"
"            const payload = await postForm(\"/api/set\", { key, value });\n"
"            if (payload && typeof payload === \"object\") {\n"
"              applyStatePayload(payload);\n"
"            }\n"
"            if (!options.quiet) setBanner(`Updated ${key}.`, \"ok\");\n"
"          } catch (error) {\n"
"            if (!options.quiet) setBanner(`Could not update ${key}: ${error.message}`, \"error\");\n"
"            throw error;\n"
"          }\n"
"        }\n"
"\n"
"        async function postSynth(data, successMessage = \"Synth updated.\") {\n"
"          try {\n"
"            const nextSynth = await postForm(\"/api/synth\", data);\n"
"            state.synth = nextSynth;\n"
"            renderSynth();\n"
"            setBanner(successMessage, \"ok\");\n"
"          } catch (error) {\n"
"            setBanner(`Synth update failed: ${error.message}`, \"error\");\n"
"          }\n"
"        }\n"
"\n"
"        function applyParamsMetadata() {\n"
"          if (!state.params) return;\n"
"          fillSelect(el.controlMode, state.params.modes || [], (value) => value);\n"
"          fillSelect(el.controlScale, state.params.scales || [], (value) => value);\n"
"          fillSelect(el.controlRoot, NOTE_NAMES);\n"
"          fillSelectFromValues(el.controlTs, state.params.time_signatures || []);\n"
"          fillSelect(el.controlLo, Array.from({ length: 9 }, (_, index) => index + 1), (value) => `C${value}`);\n"
"          fillSelect(el.controlHi, Array.from({ length: 9 }, (_, index) => index + 1), (value) => `C${value}`);\n"
"          fillSelect(el.controlPreset, state.params.synth_presets || [], (value) => value);\n"
"          fillSelect(el.controlFx, state.effects, (value) => value);\n"
"          fillSelect(el.controlPal, state.palettes, (value) => value);\n"
"\n"
"          const ranges = state.params.ranges || {};\n"
"          if (ranges.bpm) {\n"
"            el.controlBpm.min = ranges.bpm[0];\n"
"            el.controlBpm.max = ranges.bpm[1];\n"
"          }\n"
"          if (ranges.swing) {\n"
"            el.controlSwing.min = ranges.swing[0];\n"
"            el.controlSwing.max = ranges.swing[1];\n"
"          }\n"
"          if (ranges.rest) {\n"
"            el.controlRest.min = ranges.rest[0];\n"
"            el.controlRest.max = ranges.rest[1];\n"
"          }\n"
"          if (ranges.sens) {\n"
"            el.controlSens.min = ranges.sens[0];\n"
"            el.controlSens.max = ranges.sens[1];\n"
"          }\n"
"          if (ranges.bright) {\n"
"            el.controlBright.min = ranges.bright[0];\n"
"            el.controlBright.max = ranges.bright[1];\n"
"          }\n"
"          if (ranges.master) {\n"
"            el.controlMaster.min = ranges.master[0];\n"
"            el.controlMaster.max = ranges.master[1];\n"
"          }\n"
"          if (ranges.drive) {\n"
"            el.controlDrive.min = ranges.drive[0];\n"
"            el.controlDrive.max = ranges.drive[1];\n"
"          }\n"
"          if (ranges.cutoff) {\n"
"            el.controlCutoff.min = ranges.cutoff[0];\n"
"            el.controlCutoff.max = ranges.cutoff[1];\n"
"          }\n"
"          if (ranges.resonance) {\n"
"            el.controlResonance.min = ranges.resonance[0];\n"
"            el.controlResonance.max = ranges.resonance[1];\n"
"          }\n"
"          if (ranges.attack) {\n"
"            el.controlAttack.min = ranges.attack[0];\n"
"            el.controlAttack.max = ranges.attack[1];\n"
"            el.controlDecay.min = ranges.decay[0];\n"
"            el.controlDecay.max = ranges.decay[1];\n"
"            el.controlSustain.min = ranges.sustain[0];\n"
"            el.controlSustain.max = ranges.sustain[1];\n"
"            el.controlRelease.min = ranges.release[0];\n"
"            el.controlRelease.max = ranges.release[1];\n"
"          }\n"
"          if (ranges.delay_mix) {\n"
"            el.controlDelayMix.min = ranges.delay_mix[0];\n"
"            el.controlDelayMix.max = ranges.delay_mix[1];\n"
"            el.controlDelayFeedback.min = ranges.delay_feedback[0];\n"
"            el.controlDelayFeedback.max = ranges.delay_feedback[1];\n"
"          }\n"
"\n"
"          buildSegmented(\n"
"            el.outputGroup,\n"
"            OUTPUT_LABELS.map((label, index) => ({ label, value: index })),\n"
"            (value) => postSet(\"outputmode\", value)\n"
"          );\n"
"          buildSegmented(\n"
"            el.clockGroup,\n"
"            CLOCK_LABELS.map((label, index) => ({ label, value: index })),\n"
"            (value) => postSet(\"clock\", value)\n"
"          );\n"
"        }\n"
"\n"
"        function renderRuntime() {\n"
"          const runtime = state.runtime;\n"
"          if (!runtime) return;\n"
"\n"
"          state.auxReady = runtime.aux_ready !== 0;\n"
"          state.syncLocked = runtime.daw_lock !== 0;\n"
"          const modeName = state.params?.modes?.[runtime.mode] || \"Unknown\";\n"
"          const scaleName = state.params?.scales?.[runtime.scale] || \"Unknown\";\n"
"          const rootName = NOTE_NAMES[runtime.root] || \"--\";\n"
"          const outputName = OUTPUT_LABELS[runtime.outputmode] || \"--\";\n"
"          const clockName = state.syncLocked ? \"DAW Lock\" : CLOCK_LABELS[runtime.clock] || \"--\";\n"
"\n"
"          el.modePill.textContent = `Mode: ${modeName}`;\n"
"          el.outputPill.textContent = `Output: ${outputName}`;\n"
"          el.outputPill.className = \"pill\";\n"
"          el.valueMode.textContent = modeName;\n"
"          el.valueScale.textContent = scaleName;\n"
"          el.valueRoot.textContent = rootName;\n"
"          el.valueBpm.textContent = `${runtime.bpm} bpm`;\n"
"          el.valueTs.textContent = runtime.ts || \"--\";\n"
"          el.valueSwing.textContent = `${runtime.swing}%`;\n"
"          el.valueRest.textContent = fmtPercent(runtime.rest);\n"
"          el.valueSens.textContent = fmtNumber(runtime.sens, 2);\n"
"          el.valueOctave.textContent = `C${runtime.lo} - C${runtime.hi}`;\n"
"          el.valueClock.textContent = CLOCK_LABELS[runtime.clock] || \"--\";\n"
"          el.valueNoRep.textContent = runtime.nr ? \"ON\" : \"OFF\";\n"
"          el.valueFx.textContent = runtime.fxname || state.effects[runtime.fx] || \"--\";\n"
"          el.valuePal.textContent = runtime.palname || state.palettes[runtime.pal] || \"--\";\n"
"          el.valueBright.textContent = String(runtime.bright);\n"
"          el.valueVs.textContent = String(runtime.vs);\n"
"          el.valueVi.textContent = String(runtime.vi);\n"
"          el.valueOutput.textContent = outputName;\n"
"          el.valueSync.textContent = runtime.daw_sync ? (state.syncLocked ? \"LOCK\" : \"ON\") : \"OFF\";\n"
"          el.valueMute.textContent = runtime.io_muted ? \"ON\" : \"OFF\";\n"
"          el.valueRuntime.textContent = runtime.io_muted ? \"muted\" : \"steady\";\n"
"          el.lastNote.textContent = runtime.last ? noteNameFromMidi(Number(runtime.last)) : \"--\";\n"
"          el.lastVelocity.textContent = runtime.vel ? String(runtime.vel) : \"--\";\n"
"          el.clockStatus.textContent = clockName;\n"
"\n"
"          el.transportChip.textContent = `Transport: ${runtime.bpm} bpm • ${runtime.ts}`;\n"
"          el.syncLockChip.textContent = `Sync lock: ${state.syncLocked ? \"locked\" : \"free\"}`;\n"
"          el.auxReadyChip.textContent = state.auxReady\n"
"            ? \"Aux: ready\"\n"
"            : `Aux: wait ${runtime.aux_wait_ms || 0} ms`;\n"
"          el.summaryCopy.textContent =\n"
"            `${modeName} in ${scaleName} on ${rootName}, routed to ${outputName}. ` +\n"
"            `${state.auxReady ? \"Aux engine is available.\" : \"Aux engine is cooling down before it can be selected.\"}`;\n"
"          el.fxChip.textContent = `Effect: ${runtime.fxname || state.effects[runtime.fx] || \"--\"}`;\n"
"          el.paletteChip.textContent = `Palette: ${runtime.palname || state.palettes[runtime.pal] || \"--\"}`;\n"
"          el.brightnessChip.textContent = `Brightness: ${runtime.bright}`;\n"
"          el.motionChip.textContent = `Motion: ${runtime.vs} • Energy: ${runtime.vi}`;\n"
"          el.auxPill.textContent = state.auxReady\n"
"            ? \"Aux status: ready\"\n"
"            : `Aux status: wait ${runtime.aux_wait_ms || 0} ms`;\n"
"          el.ledPill.textContent = `LEDs ${runtime.fxname || \"active\"}`;\n"
"\n"
"          el.controlMode.value = String(runtime.mode);\n"
"          el.controlScale.value = String(runtime.scale);\n"
"          el.controlRoot.value = String(runtime.root);\n"
"          el.controlTs.value = String(runtime.ts || \"\");\n"
"          el.controlLo.value = String(runtime.lo);\n"
"          el.controlHi.value = String(runtime.hi);\n"
"          el.controlBpm.value = String(runtime.bpm);\n"
"          el.controlSwing.value = String(runtime.swing);\n"
"          el.controlRest.value = String(runtime.rest);\n"
"          el.controlSens.value = String(runtime.sens);\n"
"          el.controlBright.value = String(runtime.bright);\n"
"          el.controlVs.value = String(runtime.vs);\n"
"          el.controlVi.value = String(runtime.vi);\n"
"          el.controlFx.value = String(runtime.fx);\n"
"          el.controlPal.value = String(runtime.pal);\n"
"\n"
"          el.syncButton.classList.toggle(\"is-active\", Boolean(runtime.daw_sync));\n"
"          el.syncButton.textContent = runtime.daw_sync ? \"Sync enabled\" : \"Sync disabled\";\n"
"          el.muteButton.classList.toggle(\"is-active\", Boolean(runtime.io_muted));\n"
"          el.muteButton.textContent = runtime.io_muted ? \"Muted\" : \"Mute outputs\";\n"
"          el.norepButton.classList.toggle(\"is-active\", Boolean(runtime.nr));\n"
"          el.norepButton.textContent = runtime.nr ? \"No repeat ON\" : \"Keep notes moving\";\n"
"\n"
"          updateSegmented(el.outputGroup, runtime.outputmode, state.auxReady ? null : 2);\n"
"          updateSegmented(el.clockGroup, runtime.clock);\n"
"\n"
"          renderLedStack();\n"
"          renderDrumGrid();\n"
"        }\n"
"\n"
"        function renderSynth() {\n"
"          const synth = state.synth;\n"
"          if (!synth) return;\n"
"          el.controlPreset.value = String(synth.preset);\n"
"          el.controlMaster.value = String(synth.master);\n"
"          el.controlDrive.value = String(synth.drive);\n"
"          el.controlCutoff.value = String(synth.cutoff);\n"
"          el.controlResonance.value = String(synth.resonance);\n"
"          el.controlAttack.value = String(synth.attack);\n"
"          el.controlRelease.value = String(synth.release);\n"
"          el.controlDecay.value = String(synth.decay);\n"
"          el.controlSustain.value = String(synth.sustain);\n"
"          el.controlDelayMix.value = String(synth.delay_mix);\n"
"          el.controlDelayFeedback.value = String(synth.delay_feedback);\n"
"\n"
"          el.valuePreset.textContent = synth.preset_name || \"--\";\n"
"          el.valueMaster.textContent = fmtNumber(synth.master, 2);\n"
"          el.valueDrive.textContent = fmtNumber(synth.drive, 2);\n"
"          el.valueCutoff.textContent = `${Math.round(Number(synth.cutoff) || 0)} hz`;\n"
"          el.valueResonance.textContent = fmtNumber(synth.resonance, 2);\n"
"          el.valueAttack.textContent = fmtNumber(synth.attack, 2);\n"
"          el.valueRelease.textContent = fmtNumber(synth.release, 2);\n"
"          el.valueDecay.textContent = fmtNumber(synth.decay, 2);\n"
"          el.valueSustain.textContent = fmtNumber(synth.sustain, 2);\n"
"          el.valueDelayMix.textContent = fmtNumber(synth.delay_mix, 2);\n"
"          el.valueDelayFeedback.textContent = fmtNumber(synth.delay_feedback, 2);\n"
"        }\n"
"\n"
"        function renderNotes() {\n"
"          if (!state.noteList.length) {\n"
"            el.noteReadout.textContent = \"Waiting for notes...\";\n"
"          } else {\n"
"            const names = noteNamesFromList(state.noteList);\n"
"            const chord = inferChord(state.noteList);\n"
"            el.noteReadout.textContent = chord ? `${names.join(\" \")} | ${chord}` : names.join(\" \");\n"
"          }\n"
"          renderNoteStrip();\n"
"        }\n"
"\n"
"        function applyStatePayload(payload) {\n"
"          state.runtime = payload;\n"
"          renderRuntime();\n"
"          if (payload.last) {\n"
"            const lastMidi = Number(payload.last);\n"
"            if (Number.isFinite(lastMidi) && !state.noteList.length) {\n"
"              state.noteList = [lastMidi];\n"
"              renderNotes();\n"
"            }\n"
"          }\n"
"        }\n"
"\n"
"        function applyNotesPayload(payload) {\n"
"          state.noteList = Array.isArray(payload.notes) ? payload.notes.map(Number).filter(Number.isFinite) : [];\n"
"          state.noteVelocity = Number(payload.vel || payload.last_vel || 0);\n"
"          renderNotes();\n"
"        }\n"
"\n"
"        function applyDrumPayload(payload) {\n"
"          state.drumHitMask = Number(payload.hit || 0);\n"
"          state.drumMask = Number(payload.sel || state.drumMask || 0);\n"
"          renderLedStack();\n"
"          renderDrumGrid();\n"
"        }\n"
"\n"
"        let fallbackPollTimer = null;\n"
"        let fallbackPolling = false;\n"
"\n"
"        function applyLivePayload(payload) {\n"
"          if (!payload || typeof payload !== \"object\") return;\n"
"          if (payload.state) applyStatePayload(payload.state);\n"
"          if (payload.plant) addPlantPoint(payload.plant.value || 0);\n"
"          if (payload.notes) applyNotesPayload(payload.notes);\n"
"          if (payload.drum) applyDrumPayload(payload.drum);\n"
"        }\n"
"\n"
"        function stopFallbackPolling() {\n"
"          fallbackPolling = false;\n"
"          if (fallbackPollTimer !== null) {\n"
"            window.clearTimeout(fallbackPollTimer);\n"
"            fallbackPollTimer = null;\n"
"          }\n"
"        }\n"
"\n"
"        function startFallbackPolling() {\n"
"          if (fallbackPolling) return;\n"
"          fallbackPolling = true;\n"
"          const tick = async () => {\n"
"            if (!fallbackPolling) return;\n"
"            try {\n"
"              applyLivePayload(await getJson(\"/api/live\"));\n"
"              setConnection(\"BECA live\", \"status-live\");\n"
"            } catch (error) {\n"
"              setConnection(\"Reconnecting...\", \"status-warn\");\n"
"            } finally {\n"
"              if (fallbackPolling) fallbackPollTimer = window.setTimeout(tick, 700);\n"
"            }\n"
"          };\n"
"          tick();\n"
"        }\n"
"\n"
"        async function refreshAll() {\n"
"          setConnection(\"Refreshing BECA...\", \"status-live\");\n"
"          setBanner(\"Refreshing live state…\");\n"
"          try {\n"
"            const [params, effects, palettes, runtime, synth, notes, drum, plant] = await Promise.all([\n"
"              getJson(\"/api/params\"),\n"
"              getJson(\"/effects\"),\n"
"              getJson(\"/palettes\"),\n"
"              getJson(\"/api/state\"),\n"
"              getJson(\"/api/synth\"),\n"
"              getJson(\"/api/notes\"),\n"
"              getJson(\"/api/drum\"),\n"
"              getJson(\"/api/plant\")\n"
"            ]);\n"
"            state.params = params;\n"
"            state.effects = effects.list || [];\n"
"            state.palettes = palettes.list || [];\n"
"            state.synth = synth;\n"
"            applyParamsMetadata();\n"
"            applyStatePayload(runtime);\n"
"            applyNotesPayload(notes);\n"
"            applyDrumPayload(drum);\n"
"            addPlantPoint(plant.value || 0);\n"
"            renderSynth();\n"
"            setConnection(\"BECA live\", \"status-live\");\n"
"            setBanner(\"Live controls synced.\", \"ok\");\n"
"          } catch (error) {\n"
"            setConnection(\"BECA unavailable\", \"status-error\");\n"
"            setBanner(`Could not load BECA state: ${error.message}`, \"error\");\n"
"          }\n"
"        }\n"
"\n"
"        function setupRealtime() {\n"
"          const events = new EventSource(\"/events\");\n"
"          let streamHealthy = false;\n"
"          const streamFallbackTimer = window.setTimeout(() => {\n"
"            if (streamHealthy) return;\n"
"            events.close();\n"
"            startFallbackPolling();\n"
"          }, 1800);\n"
"          events.addEventListener(\"hello\", () => {\n"
"            setConnection(\"BECA live\", \"status-live\");\n"
"          });\n"
"          events.addEventListener(\"state\", (event) => {\n"
"            try {\n"
"              streamHealthy = true;\n"
"              window.clearTimeout(streamFallbackTimer);\n"
"              stopFallbackPolling();\n"
"              applyStatePayload(JSON.parse(event.data));\n"
"            } catch (error) {}\n"
"          });\n"
"          events.addEventListener(\"scope\", (event) => {\n"
"            streamHealthy = true;\n"
"            window.clearTimeout(streamFallbackTimer);\n"
"            stopFallbackPolling();\n"
"            addPlantPoint(event.data);\n"
"          });\n"
"          events.addEventListener(\"note\", (event) => {\n"
"            streamHealthy = true;\n"
"            const [, velRaw, , listRaw] = String(event.data).split(\"|\");\n"
"            const list = (listRaw || \"\")\n"
"              .split(\",\")\n"
"              .map((value) => Number(value))\n"
"              .filter(Number.isFinite);\n"
"            applyNotesPayload({ notes: list, vel: Number(velRaw || 0) });\n"
"          });\n"
"          events.addEventListener(\"drum\", (event) => {\n"
"            streamHealthy = true;\n"
"            const [hit, sel] = String(event.data)\n"
"              .split(\"|\")\n"
"              .map((value) => Number(value || 0));\n"
"            applyDrumPayload({ hit, sel });\n"
"          });\n"
"          events.onerror = () => {\n"
"            window.clearTimeout(streamFallbackTimer);\n"
"            events.close();\n"
"            setConnection(\"Reconnecting...\", \"status-warn\");\n"
"            startFallbackPolling();\n"
"          };\n"
"        }\n"
"\n"
"        function bindEvents() {\n"
"          bindRange(el.controlSens, \"sens\", (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueSens.textContent = value;\n"
"          });\n"
"          bindRange(el.controlBpm, \"bpm\", (value) => Number(value), (value) => {\n"
"            el.valueBpm.textContent = `${value} bpm`;\n"
"          });\n"
"          bindRange(el.controlSwing, \"swing\", (value) => Number(value), (value) => {\n"
"            el.valueSwing.textContent = `${value}%`;\n"
"          });\n"
"          bindRange(el.controlRest, \"rest\", (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueRest.textContent = `${Math.round(Number(value) * 100)}%`;\n"
"          });\n"
"          bindRange(el.controlBright, \"bright\", (value) => Number(value), (value) => {\n"
"            el.valueBright.textContent = String(value);\n"
"          });\n"
"          bindRange(el.controlVs, \"vs\", (value) => Number(value), (value) => {\n"
"            el.valueVs.textContent = String(value);\n"
"          });\n"
"          bindRange(el.controlVi, \"vi\", (value) => Number(value), (value) => {\n"
"            el.valueVi.textContent = String(value);\n"
"          });\n"
"\n"
"          el.controlMode.addEventListener(\"change\", () => postSet(\"mode\", el.controlMode.value));\n"
"          el.controlScale.addEventListener(\"change\", () => postSet(\"scale\", el.controlScale.value));\n"
"          el.controlRoot.addEventListener(\"change\", () => postSet(\"root\", el.controlRoot.value));\n"
"          el.controlTs.addEventListener(\"change\", () => postSet(\"ts\", el.controlTs.value));\n"
"          el.controlLo.addEventListener(\"change\", async () => {\n"
"            await postSet(\"lo\", el.controlLo.value);\n"
"            if (Number(el.controlHi.value) < Number(el.controlLo.value)) {\n"
"              el.controlHi.value = el.controlLo.value;\n"
"              await postSet(\"hi\", el.controlHi.value);\n"
"            }\n"
"          });\n"
"          el.controlHi.addEventListener(\"change\", async () => {\n"
"            await postSet(\"hi\", el.controlHi.value);\n"
"            if (Number(el.controlLo.value) > Number(el.controlHi.value)) {\n"
"              el.controlLo.value = el.controlHi.value;\n"
"              await postSet(\"lo\", el.controlLo.value);\n"
"            }\n"
"          });\n"
"          el.controlFx.addEventListener(\"change\", () => postSet(\"fx\", el.controlFx.value));\n"
"          el.controlPal.addEventListener(\"change\", () => postSet(\"pal\", el.controlPal.value));\n"
"\n"
"          el.controlPreset.addEventListener(\"change\", () =>\n"
"            postSynth({ preset: el.controlPreset.value }, \"Synth preset updated.\")\n"
"          );\n"
"          bindPreview(el.controlMaster, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueMaster.textContent = value;\n"
"          });\n"
"          el.controlMaster.addEventListener(\"change\", () =>\n"
"            postSynth({ master: el.controlMaster.value }, \"Synth master updated.\")\n"
"          );\n"
"          bindPreview(el.controlDrive, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueDrive.textContent = value;\n"
"          });\n"
"          el.controlDrive.addEventListener(\"change\", () =>\n"
"            postSynth({ drive: el.controlDrive.value }, \"Synth drive updated.\")\n"
"          );\n"
"          bindPreview(el.controlCutoff, (value) => Number(value), (value) => {\n"
"            el.valueCutoff.textContent = `${Math.round(Number(value))} hz`;\n"
"          });\n"
"          el.controlCutoff.addEventListener(\"change\", () =>\n"
"            postSynth({ cutoff: el.controlCutoff.value }, \"Filter cutoff updated.\")\n"
"          );\n"
"          bindPreview(el.controlResonance, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueResonance.textContent = value;\n"
"          });\n"
"          el.controlResonance.addEventListener(\"change\", () =>\n"
"            postSynth({ resonance: el.controlResonance.value }, \"Resonance updated.\")\n"
"          );\n"
"          bindPreview(el.controlAttack, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueAttack.textContent = value;\n"
"          });\n"
"          el.controlAttack.addEventListener(\"change\", () =>\n"
"            postSynth({ attack: el.controlAttack.value }, \"Attack updated.\")\n"
"          );\n"
"          bindPreview(el.controlRelease, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueRelease.textContent = value;\n"
"          });\n"
"          el.controlRelease.addEventListener(\"change\", () =>\n"
"            postSynth({ release: el.controlRelease.value }, \"Release updated.\")\n"
"          );\n"
"          bindPreview(el.controlDecay, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueDecay.textContent = value;\n"
"          });\n"
"          el.controlDecay.addEventListener(\"change\", () =>\n"
"            postSynth({ decay: el.controlDecay.value }, \"Decay updated.\")\n"
"          );\n"
"          bindPreview(el.controlSustain, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueSustain.textContent = value;\n"
"          });\n"
"          el.controlSustain.addEventListener(\"change\", () =>\n"
"            postSynth({ sustain: el.controlSustain.value }, \"Sustain updated.\")\n"
"          );\n"
"          bindPreview(el.controlDelayMix, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueDelayMix.textContent = value;\n"
"          });\n"
"          el.controlDelayMix.addEventListener(\"change\", () =>\n"
"            postSynth({ delay_mix: el.controlDelayMix.value }, \"Delay mix updated.\")\n"
"          );\n"
"          bindPreview(el.controlDelayFeedback, (value) => Number(value).toFixed(2), (value) => {\n"
"            el.valueDelayFeedback.textContent = value;\n"
"          });\n"
"          el.controlDelayFeedback.addEventListener(\"change\", () =>\n"
"            postSynth(\n"
"              { delay_feedback: el.controlDelayFeedback.value },\n"
"              \"Delay feedback updated.\"\n"
"            )\n"
"          );\n"
"\n"
"          el.syncButton.addEventListener(\"click\", async () => {\n"
"            const next = state.runtime && state.runtime.daw_sync ? 0 : 1;\n"
"            await postSet(\"daw_sync\", next);\n"
"          });\n"
"          el.muteButton.addEventListener(\"click\", async () => {\n"
"            const next = state.runtime && state.runtime.io_muted ? 0 : 1;\n"
"            await postSet(\"mute\", next);\n"
"          });\n"
"          el.norepButton.addEventListener(\"click\", async () => {\n"
"            const next = state.runtime && state.runtime.nr ? 0 : 1;\n"
"            await postSet(\"norep\", next);\n"
"          });\n"
"          el.randomButton.addEventListener(\"click\", async () => {\n"
"            try {\n"
"              await fetch(\"/rand\");\n"
"              setBanner(\"Randomized live system.\", \"ok\");\n"
"            } catch (error) {\n"
"              setBanner(`Randomize failed: ${error.message}`, \"error\");\n"
"            }\n"
"          });\n"
"          el.refreshButton.addEventListener(\"click\", refreshAll);\n"
"          el.testChordButton.addEventListener(\"click\", async () => {\n"
"            try {\n"
"              await getJson(\"/api/synth/test\");\n"
"              setBanner(\"Aux test chord triggered.\", \"ok\");\n"
"            } catch (error) {\n"
"              setBanner(`Aux test chord failed: ${error.message}`, \"error\");\n"
"            }\n"
"          });\n"
"          el.presetResetButton.addEventListener(\"click\", async () => {\n"
"            await postSynth({ reset: 1 }, \"Synth preset reset.\");\n"
"          });\n"
"        }\n"
"\n"
"        function seedVisuals() {\n"
"          for (let i = 0; i < 12; i += 1) {\n"
"            state.plantPoints[i] = 0.35 + Math.sin(i * 0.45) * 0.08;\n"
"          }\n"
"          renderChart();\n"
"          renderNoteStrip();\n"
"          renderLedStack();\n"
"          renderDrumGrid();\n"
"        }\n"
"\n"
"        async function init() {\n"
"          seedVisuals();\n"
"          bindEvents();\n"
"          window.setInterval(() => {\n"
"            if (document.hidden || !state.runtime) return;\n"
"            if (Number(state.runtime.led_display_mode) === LED_DISPLAY_SETTING &&\n"
"                Number(state.runtime.encoder_setting) === 4) {\n"
"              renderLedStack();\n"
"            }\n"
"          }, 80);\n"
"          await refreshAll();\n"
"          setupRealtime();\n"
"        }\n"
"\n"
"        init().catch((error) => {\n"
"          setConnection(\"BECA unavailable\", \"status-error\");\n"
"          setBanner(`Initialization failed: ${error.message}`, \"error\");\n"
"        });\n"
"      })();\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;
